# Generated by Django 2.2 on 2019-12-06 01:49

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_caa',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_caa_member',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(max_length=255, null=True, verbose_name='Apellido usuario'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
